### ISSUE TITLE
Übersetzungen werden nicht für contentHtml genutzt

### ISSUE THREAD

**Issue by Diginix** [foxriver76/ioBroker.bring#149]
Die API liefert für (Speise)Eis das Wort "Glacé". In bring.0.x.enumSentence steht dann auch "Eis" statt Glacé, weil es anscheinend über das Mapping aus bring.0.x.translation richtig übersetzt wird. In den html Objekten (contentHtml, contentHtmlNoHead) steht aber weiterhin Glacé.
Wäre toll wenn auch dort der Inhalt übersetzt würde.

bring: 1.7.15
js-controller: 4.0.23
nodejs: 14.19.3

**Comment by foxriver76** [comment]
Bitte 1.7.16 testen

**Comment by Diginix** [comment]
Funktioniert für die html Objekte bei mir. Aber im JSON in bring.0.x.content steht noch der nicht übersetzte Wert.
Oder ist das das Quellobjekt mit dem Wert der API?

**Comment by foxriver76** [comment]
Quasi Quellobjekt, falls benötigt lege ich einen extra translated state an.

**Comment by Diginix** [comment]
Ne, dann passt es für mich so. Ich nutze das html Objekt in der VIS.
Danke für die prompte Umsetzung!

**Comment by foxriver76** [comment]
Gerne, danke fürs Testen

**Comment by Diginix** [comment]
Eine Kleinigkeit ist nun etwas tricky. Wenn man über bring.0.x.removeItem ein übersetzten Eintrag entfernen will, muss man das original Wort kennen und eingeben. Wäre es denkbar dass Texte die man in das Objekt schreibt gegen das translation mapping geprüft werden und falls auf der json Liste vorhanden, dann mit dem passenden original Wort an die API zum Entfernen gegeben werden?

**Comment by foxriver76** [comment]
Die aktuelle Struktur ist stark im Widget verankert, wird also auf neue States mit Translated Suffix hinaus laufen für `add`, `move` und `remove`

**Comment by foxriver76** [comment]
Bitte Testen mit den neuen States, war doch etwas mehr Restrukturierung, was dem Adapter allerdings nicht schadet. *gg*

**Comment by Diginix** [comment]
Hinzufügen mit Wort "Eis" funktionierte über bring.0.x.saveItem bereits bzw. mit v1.8.0. Ob auch mit 1.7.x weiß ich nicht.
Mit bring.0.x.removeItemTranslated lässt es sich nun mit Wort "Eis" und interessanterweise weiterhin auch mit "Glacé" entfernen und ebenso mit beiden Wörtern über bring.0.x.saveItemTranslated hinzufügen. Steht aber immer korrekt als "Eis" in den *translated Objekten.

Bisher habe ich moveTo nicht verwendet, aber wenn ich Dinge mit Spezifikation dort nur mit dem Produktnamen eingebe, werden sie bei Content nicht entfernt. K.a. ob das schon immer so war.
Konkret ich füge "Eis, Schoko" über saveItem oder saveItemTranslated hinzu.
Über removeItemTranslated kann ich mit nur "Eis" das Produkt aus der Liste löschen ohne "Schoko" mit anzugeben.
Wenn ich aber "Eis" oder "Eis, Schoko" in moveToRecentContentTranslated oder moveToRecentContent eintrage, kommt es nur zu recentContent* hinzu. Ich hätte erwartet, dass es dann aber wie beim Abhaken in der bring App von der content* Liste verschwindet. Es heißt ja auch move und nicht copy ;-)

Da ich move nicht nutze, sind meine Wünsche mit 1.8.0 aber nun voll erfüllt.

**Comment by foxriver76** [comment]
Hm, ich stelle es gleich mal nach, aber eigentlich ist das genau das was die API macht und das Widget ja entsprechend seit langem genau so funktioniert ohne da besondere Magie zu haben. Da wäre ich jetzt stark verwundert wenn was nicht mehr tut oder ich habe es kaputt gemacht mit dem neusten Update.

**Comment by foxriver76** [comment]
Also mit 1.7.13 und dem Artikel `Milch` funktioniert es problemlos. Ich update mal.

**Comment by foxriver76** [comment]
Das einzige wann der Artikel nicht enfernt wird, ist wenn er nicht auf der Liste ist, dann wird er in recent gepackt, aber nirgends entfernt logischerweise.

**Comment by Diginix** [comment]
Wenn du Milch in content* hast und in moveTo "Milch" schreibst, verschwindet er in content*?
Komisch. Dann lag es doch an der zusätzlichen "specification". Wenn man "Milch, 3" in saveTo packt und nur "Milche" in remove, passt es. Schreibt man aber "Milche" in moveTo, klappt es nicht und auch nicht mit "Milche, 3" in moveTo.

**Comment by Diginix** [comment]
Hab gerade auch noch mal ein "Test, 7" Artikel über save angelegt und konnte in mit "Test" in moveToRecentContentTranslated korrekt nach recent bewegen und er verschwand auch in content*.
Irgendwas hat aber vorhin da nicht funktioniert. Aber im Moment nicht reproduzierbar. Ich aktualisiere nochmal über GIT und teste bei Gelegenheit weiter.
