### ISSUE TITLE
Other languages?

### ISSUE THREAD

**Issue by MatteoD77** [foxriver76/ioBroker.bring#18]
It is possible to have items in Italian language, like in the iOs App.
I don't know why but the adapter is translating everything in german....

Thank you so much
Matteo

**Comment by foxriver76** [comment]
Good point. I haven't tested it until now but I could imagine that it is due to the header country in https://github.com/foxriver76/node-bring-api/blob/fee639ef112f3287e5fa1c9da91c59c502eb8fe5/lib/bring.js#L30

I will check this.

**Comment by MatteoD77** [comment]
Thank you so much! 
Have a nice week end! 
I will stay tuned!

**Comment by foxriver76** [comment]
Unfortunately changing the related header line to another country did not do the trick. Also an Accept-Language Header did not work. Maybe it is possible to find out the necessary information using wireshark 🦈

**Comment by MatteoD77** [comment]
Ah ok thank you!

**Comment by foxriver76** [comment]
In the web app the list language is changed as follows:
 Post to 
https://api.getbring.com/rest/v2/bringusersettings/<user-uuid>/<list-uuid>/listArticleLanguage with parameter `value: pl-PL` for Poland

```
Host: api.getbring.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: application/json, text/plain, */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://web.getbring.com/app/settings/lists
Content-Type: application/x-www-form-urlencoded
X-BRING-API-KEY: <api-key>
X-BRING-CLIENT: webApp
X-BRING-CLIENT-SOURCE: webApp
X-BRING-USER-UUID: <user-uuid>
X-BRING-COUNTRY: DE
X-BRING-CLIENT-INSTANCE-ID: Web-<id>
Authorization: Bearer <Token>
Content-Length: 11
Origin: https://web.getbring.com
Connection: keep-alive
Cookie: _ga=GA1.2.482787696.1562654361; _gid=<gid>
```

**Comment by foxriver76** [comment]
How-To get Bearer Token:
Login

Host: api.getbring.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: application/json, text/plain, */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://web.getbring.com/login
Content-Type: application/x-www-form-urlencoded
X-BRING-API-KEY: cof4Nc6D8saplXjE3h3HXqHH8m7VU2i1Gs0g85Sp
X-BRING-CLIENT: webApp
X-BRING-CLIENT-SOURCE: webApp
X-BRING-CLIENT-INSTANCE-ID: Web-t2pGHaiSOS6GIXt9R0nenilTJ2MV3zuj
Content-Length: 48
Origin: https://web.getbring.com
Connection: keep-alive
Cookie: _ga=GA1.2.482787696.1562654361; _gid=GA1.2.1444567264.1562654361; _gat_bringWebAppGeneralTracker=1

param:
email: mail
password: pw

the rest of v2 API is very equal to v1 so I will probably update https://github.com/foxriver76/node-bring-api to v2 so we can set languages and do reverse engineering

**Comment by foxriver76** [comment]
Auth is implemented. But the locale is not translating the the articles, instead the locale is used to get a json file and do the translations like GET request at `https://web.getbring.com/locale/articles.fr-FR.json`
for france

```
Host: web.getbring.com 
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: application/json, text/plain, */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://web.getbring.com/app/lists/0
X-BRING-API-KEY: cof4Nc6D8saplXjE3h3HXqHH8m7VU2i1Gs0g85Sp
X-BRING-CLIENT: webApp
X-BRING-CLIENT-SOURCE: webApp
X-BRING-USER-UUID: 15608336-96c8-421a-82d3-37e1f5e37169
X-BRING-COUNTRY: DE
X-BRING-CLIENT-INSTANCE-ID: Web-rFi1nPDG9zOKhjlqszUIz4hdkgfIYxdR
Authorization: Bearer <token>
Connection: keep-alive
Cookie: bla
```

**Comment by foxriver76** [comment]
Functionality is implemented in v1.2.0 of the bring-api interface with https://github.com/foxriver76/node-bring-api/commit/c582eed5bf9002babb1e0017c1adf49d7bc6a4e8

Still have to implement it in the adapter. We will only use translations in the frontend.

**Comment by foxriver76** [comment]
@MatteoD77 Could you please install from GitHub and check if the translation state for your list contains the correct dictionary, so it should contain the 'swiss-german' items mapped on italian items.

**Comment by foxriver76** [comment]
It is fully implemented in GitHub version
