### ISSUE TITLE
Schwyzerdütsch? 

### ISSUE THREAD

**Issue by Haifeif** [foxriver76/ioBroker.bring#215]
**Describe the bug**
Wenn in der Liste auf einem W10 PC, einem Android Telefon und einem I-Phone "Hähnchenbrust" angezeigt wird, 
der ioBroker Adapter daraus aber "Poulet Brüstli" macht, ist irgend etwas verdreht! 😂

Ich möchte das nicht wirklich als Bug bezeichnen, eher als Irritation!

LG Uwe

PS: Der Adapter ist Klasse!

**Comment by foxriver76** [comment]
Die Bring API arbeitet intern auf Schweizerdeutsch und übersetzt alles dorthin, wo genau hast du das Problem? 

Der content State hat das was die API liefert und wird Schweizerdeutsch beinhalten. Das Widget etc sollte alles in die in ioBroker eingestellte Sprache übersetzen wenn verfügbar.

**Comment by Haifeif** [comment]
Ich verstehe nur Deutsch. 😁
Sorry, ich konnte nicht widerstehen. Aber Diene Frage habe ich nicht verstanden. Ich gebe per Sprachbefehl an Alexa "Hähnchenbrust" ein, und der ioBroker Adapter gibt mir "Poulet" zurück. 

Meinst Du das folgende?

bring.0.5a2b4e69-0318-4e79-9b09-480742521460.recentContent beinhaltet Hähnchenbrust 
bring.0.5a2b4e69-0318-4e79-9b09-480742521460.content beinhaltet Pouletbrüstli 

LG Uwe

**Comment by Haifeif** [comment]
Case closed, I live with it.

**Comment by Haifeif** [comment]
Case closed, I live with it.
