### ISSUE TITLE
Bug: Can not add new objects after changing views

### ISSUE THREAD

**Issue by AbdulAlBane** [foxriver76/ioBroker.bring#24]
The first time, the shopping list is used, it works fine. If the user changes the views in iobroker VIS to another view and comes back later to the view containing the shopping list, no new objects can be added to the list anymore. Neither <return> nor pressing the <+> button do trigger the adding of the object in the text field. This actually makes the list not usable for me in a multi-view visualization.

**Comment by foxriver76** [comment]
Are you using slider tabs?

**Comment by AbdulAlBane** [comment]
No, I am using the metro-style tile-navigation buttons to switch back and forth between different views.

**Comment by foxriver76** [comment]
which Browser? Have you tried anonymous mode (or deleting the cookies)? Have you tried another browser?

**Comment by AbdulAlBane** [comment]
Issue occurs in Safari on iOS 12 as well in Edge and Chrome using Windows 10. But I just found a possible solution: If I change the flag "Lösche nicht aktive Views" to "Nie" within the Setup/Einstellungen tab in iobroker, the bug does not appear. So probably once the view is removed from memory and newly instantiated when opened again, the connection to the old shopping-list session is lost?

**Comment by foxriver76** [comment]
I assume that it’s the same issue as by using slider tabs but I will check later

**Comment by foxriver76** [comment]
I've installed metro widgets added something to my list, switched to another view by metro navigation, switched back to my list via metro navigation and everything is still working.
