### ISSUE TITLE
Only first word for long shopping items with two+ words is shown

### ISSUE THREAD

**Issue by AbdulAlBane** [foxriver76/ioBroker.bring#25]
If a shopping item contains two+ words and the number of characters in both words exceed a certain value, only the first word of the item is displayed in the overview list.

Example: "Gewürztes Hackfleisch" will be shown in the list only as "Gewürztes". "Hackfleisch" is not broken down to a separate line and displayed.

![image](https://user-images.githubusercontent.com/37419381/59029338-54a65100-885e-11e9-9656-24efad8271b4.png)

**Comment by foxriver76** [comment]
Behavior is now: Text size will be reduced via binary search until it fits 95 % of the container. If the text size is already the minimum and the text is still to long, only 95 % will be shown and overflow will be hidden like in the past versions.
