### ISSUE TITLE
Widget stellt keine Einträge dar und es lässt sich nichts hinzufügen

### ISSUE THREAD

**Issue by WLAN-Kabel** [foxriver76/ioBroker.bring#28]
Das Widget zeigt die ausgewählte Liste in der View nicht an und es lässt sich auch nichts über das Widget zur Liste hinzufügen.

![grafik](https://user-images.githubusercontent.com/53860633/62616463-dcb4df80-b90f-11e9-843a-b3de7aa892bf.png)

![grafik](https://user-images.githubusercontent.com/53860633/62616576-30bfc400-b910-11e9-99e0-4d29f70c1447.png)

**Versionen:**
 - Adapter version: 1.6.2
 - JS-Controller version: 1.5.14
 - Node version: 8.15.0
 - Operating system: Raspbian 9.6

**Comment by foxriver76** [comment]
.content hinter ListenID entfernen in der Widget Config

**Comment by Elektronikwelt** [comment]
ich habe das gleiche Problem mit dem Widget. Habe als ListenID den Hauptordner "Channel" verwendet. Was muss ich beachten in der Einstellung. Daten sind alle da werden aber im Widget nicht ausgegeben

**Comment by foxriver76** [comment]
Mal einen anderen Browser probiert bzw. privater Modus um Cache und Co auszuschließen? Ansonsten mal schauen was in der Browserkonsole für ein Fehler gemeldet wird.
