### ISSUE TITLE
Token Error

### ISSUE THREAD

**Issue by vr6syncro** [foxriver76/ioBroker.bring#29]
**Describe the bug**
Moin, ich habe es aktuell total oft das mit der Adapter folgenden Fehler rausgibt:
`

bring.0 | 2019-09-07 14:03:58.483 | warn | Cannot get lists: StatusCodeError: 401 - "{\"message\":\"JWT access token is not valid\",\"errorcode\":201}"
-- | -- | -- | --

`

Ein Restart des Adapters hilft. Er wird sich dann bestimmt einen neuen Token ziehen.
Komisch finde ich es nur das es gehäuft seit einigen Tagen auftritt. Vielleicht haben die irgendwas am Code geändert?

Version 1.6.3

**Comment by foxriver76** [comment]
Hm also ich kann es bei mir nicht nachstellen, wie viel Zeit vom Adapterstart bis zur Meldung ca.? Eigentlich darf es erst nach 7 Tagen ablaufen, werde mal ein re Auth einbauen.

**Comment by vr6syncro** [comment]
Hi, 7 Tage waren es nicht. Ich denke so 2-4 Tage. Hatte es mir aber leider nicht notiert. Ein reAuth bei dem Fehler wäre top. Ich hatte es mit einem Adapter Restart bislang immer lösen können.

**Comment by foxriver76** [comment]
Sollte mit https://github.com/foxriver76/ioBroker.bring/commit/8e1c19e12d9eca6b768e64680859a52c2f3bcea5 funktionieren.
