### ISSUE TITLE
Widget stellt keine Icons dar

### ISSUE THREAD

**Issue by CKMartens** [foxriver76/ioBroker.bring#41]
**Describe the bug**
Das Widget stellt keine Icons dar, ein hinzufügen von Artikeln zur Bring-Liste ist auch nicht möglich. In der Entwicklerkonsole von Chrome erscheint folgender Fehler:
`Uncaught (in promise) TypeError: Cannot read property 'attr' of undefined
    at renderPage (index.html:4028)
    at eval (tplBringShoppingList.js:103)`

Als ListenID habe ich wie angegeben nur das Objekt mit der ListeID von Bring! genoommen
![image](https://user-images.githubusercontent.com/19702758/80026667-ccb34f00-84e2-11ea-9c9f-c6171dc78967.png)

**Versions:**
 - Adapter version: 1.7.1
 - JS-Controller version: 3.0.14
 - Node version: 10.20.1
 - Operating system: Linux (Ubuntu 18.04.4 LTS)

**Comment by foxriver76** [comment]
Hm.. bei dir ist in
https://github.com/foxriver76/ioBroker.bring/blob/7bdd40054b672fecdd3ac5418e601d00d50d29aa/widgets/bring.html#L583
`that.data` undefined... kanns bei mir leider nicht nachstellen mit Google Chrome 81.0.4044.92 
auf Ubuntu 18.04. Mal einen anderen Browser probiert? Da müsste eigentlich grundlegend was schief laufen, damit das dort undefined ist.. ging es mal und irgendetwas verändert? Web geupdated oder sowas? ;-)

**Comment by CKMartens** [comment]
Ich habe das Problem mit Fully Browser und Chrom auf dem Tablet, mit Chrome und Firefox auf dem PC.

Die einzige Änderung die ich in den letzte Monaten gemacht habe, ist die VM auf einen anderen Proxmox-Server zu ziehen.

**Comment by CKMartens** [comment]
Ich habe gerade die Instanz gelöscht, den Adapter neu installiert und meine Zugangsdaten eingegeben. In der App und im Web melde ich mich via Google-Account an. Also habe ich meine Google-Email mit zugehörigen Passwort eingegeben. Jetzt kommt es zu einem Login-Fehler:
`

bring.0 | 2020-04-23 07:17:40.090 | warn | (1844) Cannot Login: StatusCodeError: 401 - "{\"message\":\"email password combination not existing\",\"errorcode\":200}"
-- | -- | -- | --
bring.0 | 2020-04-23 07:17:39.777 | warn | (1844) Cannot get lists: StatusCodeError: 401 - "{\"message\":\"JWT access token is not valid\",\"errorcode\":201}"
bring.0 | 2020-04-23 07:17:39.459 | warn | (1844) Cannot get user settings: StatusCodeError: 401 - "{\"message\":\"JWT access token is not valid\",\"errorcode\":201}"
bring.0 | 2020-04-23 07:17:39.010 | info | (1844) [LOGIN] Reconnection in 30 seconds
bring.0 | 2020-04-23 07:17:39.009 | warn | (1844) Cannot Login: StatusCodeError: 401 - "{\"message\":\"email password combination not existing\",\"errorcode\":200}"

`

**Comment by foxriver76** [comment]
Also geht es bei dir in keinem Browser welchen du getestet hast? 
Ne, Widget ist eigentlich völlig unabhängig ob Passwort Korrekt und solche Späße. Welche Version hat denn der Web Adapter und welche der vis Adapter? Bring Adapter funktioniert sonst, also die States sind alle gefüllt nehme ich an?

**Comment by CKMartens** [comment]
Die States sind gefüllt, wenn ich im State bring.0.xxxxxxx.saveItem etwas eingebe kommt es in die Liste. Auch das Entfernen mit bring.0.xxxxxxx.removeItem klappt. Soweit funktioniert der Adapter und die Instanz. Nur werden eben im VIS nichts angezeigt.
VIS ist in der Version 1.2.6 und Webist 3.0.4. JS ist 3.0.17, aber es ging auch mit der 2.x nicht

**Comment by foxriver76** [comment]
Es gibt eine Sache die ich mir vorstellen könnte, dass das Problem verursachen kann. Evtl überschreibt ein anderes Widget die Variable.. ich mache nachher mal eine 1.7.2

**Comment by foxriver76** [comment]
Maybe fixed with https://github.com/foxriver76/ioBroker.bring/commit/fefdefcb6bf1ba80df573f1234eb269b1d7eb4e0

Sobald 1.7.2 bei dir auftaucht, bitte mal ausprobieren.

**Comment by CKMartens** [comment]
Ich habe die 1.7.2 über Github installiert. Danke, jetzt läuft es einwandfrei.

![image](https://user-images.githubusercontent.com/19702758/80087568-90700500-855b-11ea-9d7e-359f5a3937b1.png)

**Comment by foxriver76** [comment]
Top, danke fürs Feedback ;-)
