### ISSUE TITLE
Feature request für Widget: Auswahl für "Listen ID"

### ISSUE THREAD

**Issue by Mic-M** [foxriver76/ioBroker.bring#42]
Schön wäre, wenn man in VIS zwischen verschiedenen Bring!-Listen umschalten könnte. D.h. der Widget-Eigenschaft "Listen ID" unterschiedliche Listen zuordnen zu können, oder noch besser optionales Pull-Down-Menü mit den zur Verfügung stehenden Listen (z.B. per Adapter-Admin konfigurierbar)
Danke

**Comment by foxriver76** [comment]
Hm für sowas gibt es andere Widgets die mehrere Widgets kapseln können. Wüsste nicht warum so eine allgemeine Funktion in einen speziellen Adapter sollte.

**Comment by Mic-M** [comment]
Ziel ist, mehrere Widgets zu vermeiden ;) 

Ich konnte es aber über Binding und ohne eigenen Datenpunkt wie folgt lösen:
1) Pro Bring!-Liste ein Widget "Button - State" im VIS hinzufügen. In diesen Widgets jeweils unter "Objekt ID" beliebigen Text, z.B. `visDummyBring`* und unter "Wert" den jeweiligen Bring-Datenpunkt der Liste, z.B. `bring.0.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`
2) Im Bring!-Widget unter "Listen ID" eintragen: `{visDummyBring}`

Damit kann dann über die Buttons durch die einzelnen Widgets geschaltet werden. Ähnlich geht das auch mit anderen Widgets, wie z.B. Select Widget.

**Comment by foxriver76** [comment]
Schön dass du es für dich lösen konntest. Ich sehe so eine Funktionalität wie gesagt in anderen Widgets wie zB Slider Tabs und co. Diese können dann unabhängig vom speziellen Widget genutzt werden um zwischen Widgets der gleichen oder auch anderen Art zu wechseln.
