### ISSUE TITLE
Bring! dont start

### ISSUE THREAD

**Issue by amnesia106** [foxriver76/ioBroker.bring#5]
Hi, 
when is start the Bring! apdater, the went to red and in the log show this: 
`
host.debianvm | 2019-03-08 07:12:07.596 | error | instance system.adapter.bring.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2019-03-08 07:12:07.596 | error | by controller[0]: at startup (bootstrap_node.js:160:9)
Caught | 2019-03-08 07:12:07.596 | error | by controller[0]: at run (bootstrap_node.js:394:7)
Caught | 2019-03-08 07:12:07.596 | error | by controller[0]: at Module.runMain (module.js:611:10)
Caught | 2019-03-08 07:12:07.596 | error | by controller[0]: at Function.Module._load (module.js:445:3)
Caught | 2019-03-08 07:12:07.596 | error | by controller[0]: at tryModuleLoad (module.js:453:12)
Caught | 2019-03-08 07:12:07.596 | error | by controller[0]: at Module.load (module.js:494:32)
Caught | 2019-03-08 07:12:07.595 | error | by controller[0]: at Object.Module._extensions..js (module.js:586:10)
Caught | 2019-03-08 07:12:07.595 | error | by controller[0]: at Module._compile (module.js:549:28)
Caught | 2019-03-08 07:12:07.595 | error | by controller[0]: at Object.runInThisContext (vm.js:97:10)
Caught | 2019-03-08 07:12:07.595 | error | by controller[0]: at createScript (vm.js:56:10)
Caught | 2019-03-08 07:12:07.595 | error | by controller[0]: SyntaxError: Unexpected token ...
Caught | 2019-03-08 07:12:07.595 | error | by controller[0]: ^^^
Caught | 2019-03-08 07:12:07.595 | error | by controller[0]: options = {...options, ...{name: `bring`}};
Caught | 2019-03-08 07:12:07.595 | error | by controller[0]: /opt/iobroker/node_modules/iobroker.bring/main.js:25

`

node version is 6.16.0

**Comment by foxriver76** [comment]
This adapter requires at least node 8.0

Von meinem iPhone gesendet
