### ISSUE TITLE
Keine ICONS kein Eintrag möglich

### ISSUE THREAD

**Issue by BobaFett98** [foxriver76/ioBroker.bring#57]
Hallo,
vllt kann mir wer weiter helfen.
Leider werden mir keine Icons angezeigt genauso wenig kann ich nichts in die Liste eintragen.
Habe Version 1.7.3 habe aber auch schoon die v. 1.7.2 ausprobiert. Browser habe ich Opera, chrome und Internet am Windows PC versucht und Chrome Am Android Handy.
Habe auch drauf geachtet als ID den Ordner zu wählen.
Nodejs Ist  auf der 10er version.
IOBroker läuft über den Raspi4 
Danke für den Adapter. Coole Idee.

MFG Jan Eric Quadflieg

**Comment by foxriver76** [comment]
Vermutlich gibt es einen Fehler in der Browser Konsole beim Laden des Widgets bitte da mal nachschauen.

**Comment by BobaFett98** [comment]
Ich habe mir mal die Console angeschaut und im Opera Browser über Windows bekomme ich diese Fehlermeldung.

index.html:4073 Uncaught (in promise) TypeError: Cannot read property 'attr' of undefined
    at renderPage (index.html:4073)
    at sentryWrapped (helpers.ts:85)

**Comment by foxriver76** [comment]
Zeig mal bitte den Output von `cat /opt/iobroker/iobroker-data/files/vis/widgets/bring.html | grep renderPage` im Terminal ausgeführt.

**Comment by BobaFett98** [comment]
Sorry in welchen Terminal genau bin da leider noch nicht so bewandert drin

**Comment by BobaFett98** [comment]
Hallo also ich habe die Befehle in den Raspberry PI Terminal eingegeben. Denke mal das ist richtig. Der erstebefehlt hat geklappt  beim 2.  grep renderPage passiert nichts.  Bin leider noch nicht so in der Ganzen Materie drin :/
![image](https://user-images.githubusercontent.com/25724839/101054316-112ebf00-3589-11eb-9ba1-6a2e748b0dba.png)

**Comment by BobaFett98** [comment]
![image](https://user-images.githubusercontent.com/25724839/101054555-4cc98900-3589-11eb-8742-0c49b6afa8eb.png)
Glaube das ist es oder?

**Comment by foxriver76** [comment]
Alles Gut, das passt ich baue mal was ein um den Fehler einzugrenzen.

**Comment by foxriver76** [comment]
Probier mal bitte die 1.7.4

**Comment by BobaFett98** [comment]
![image](https://user-images.githubusercontent.com/25724839/101162587-d4b79d80-3632-11eb-8d74-31d1ad83c899.png)
Bekomme jetzt diese Fehlermeldung im Browser( Opera unter Windows)

![image](https://user-images.githubusercontent.com/25724839/101162867-2d873600-3633-11eb-92bf-bbdfeb18f5e7.png)

**Comment by BobaFett98** [comment]
Läuft vielen vielen Dank.

**Comment by foxriver76** [comment]
Wie läuft es nun?

**Comment by BobaFett98** [comment]
ja hab jetzt 1.7.5 drauf

**Comment by foxriver76** [comment]
Von Github installiert? Kannst du nochmal den Output zeigen `cat /opt/iobroker/iobroker-data/files/vis/widgets/bring.html | grep renderPage` hiervon? Muss da nochmal was ändern.

**Comment by BobaFett98** [comment]
Dachte da du oben was geändert hast das ich nochmal mein Bring aktualisiere.

**Comment by foxriver76** [comment]
Ja passt auch aber ich bräuchte nochmal die Ausgabe von `cat /opt/iobroker/iobroker-data/files/vis/widgets/bring.html | grep renderPage` um es zu validieren

**Comment by BobaFett98** [comment]
Sorry der gibt mir nichts mehr an bei dem befehl.
hab den Raspi, IObroker und den Adapter neugestartet
![image](https://user-images.githubusercontent.com/25724839/101173154-6c70b800-3642-11eb-8ba6-88d99ca9e47c.png)

**Comment by foxriver76** [comment]
Perfekt, dann passt es.
