### ISSUE TITLE
Bring Widget wird nicht in iobroker.vis Android App V2.0.3 angezeigt

### ISSUE THREAD

**Issue by lwalpurgis** [foxriver76/ioBroker.bring#59]
Das Widget wird im Browser korrekt angezeigt, jedoch nicht in der Iobroker.vis Android App. Ich bin mir unsicher, ob dies ein Bring Problem oder ein Problem der App ist. Danke.

**Comment by foxriver76** [comment]
Sollte problemlos auch in älteren Browsern laufen, bei der vis Android App, kommt man meines Wissens leider schwer bis gar nicht an die Fehlermeldungen, daher kann ich da wenig machen. Welche Adapterversion wird denn genutzt?

**Comment by lwalpurgis** [comment]
Ich nutze die Adapterversion 1.7.3 und im Browser funktioniert alles wunderbar, jedoch nur in der Android App nicht.

**Comment by foxriver76** [comment]
Vermute fast, dass man auf einen neuen Build der App warten muss, da der aktuelle Stand des Widgets immer nur zum Build Zeitpunkt rein kommt. Für nen Rebuild habe ich schon ein Issue aus anderen Gründen erstellt gehabt: https://github.com/ioBroker/ioBroker.vis.cordova/issues/38

**Comment by mako833** [comment]
Ich hab das selbe Problem, jedoch auch wen ich mit dem Browser über die Cloud (iobroker.pro) gehe. Lokal funktioniert alles einwandfrei! Danke

**Comment by foxriver76** [comment]
> Ich hab das selbe Problem, jedoch auch wen ich mit dem Browser über die Cloud (iobroker.pro) gehe. Lokal funktioniert alles einwandfrei! Danke

Falls das Problem noch existent ist am besten mal bei ioBroker.cloud als Issue melden.

https://github.com/ioBroker/ioBroker.cloud/issues
