### ISSUE TITLE
Sign in with google

### ISSUE THREAD

**Issue by trinitywhm** [foxriver76/ioBroker.bring#60]
When I choose the option "sign in with google" do it work also with the adapter? When I enter my credentials the adapter cannot connect with bring.

**Comment by foxriver76** [comment]
Yes, I also have sign in with google working.

**Comment by electron23** [comment]
Funktioniert bei mir leider auch nicht. Muss man auf was Spezielles achten? 

Ich habe meine Google Emailadresse und mein Google Kennwort eingetragen, jedoch verbindet er sich nicht zu bring.

**Comment by foxriver76** [comment]
Habe gerade mal nachgeschaut, ich habe auch ein separates Passwort obwohl auch der Google Sign-In läuft.

Also auf https://web.getbring.com einloggen und ein separates Passwort vergeben ist wohl nötig.

**Comment by electron23** [comment]
Das ging ja schnell! :-)
Habs genauso gemacht wie du beschrieben hast und es hat jetzt funktioniert.

Vielen Dank für deine Arbeit und den schnellen Support.
