### ISSUE TITLE
no sync and no connections to the API

### ISSUE THREAD

**Issue by buehlisiobroker** [foxriver76/ioBroker.bring#61]
Sorry, bekomme seit einigen Tagen keine Verbindungen mehr über der Adapter.
Die Zugangsdaten habe ich bereits überprüft, den Apdater habe ich schon gelöscht und neu installiert. 

bring.0 | 2021-03-19 07:36:00.433 | warn | (13023) Error: Cannot get lists: Error: getaddrinfo ENOTFOUND api.getbring.com
bring.0 | 2021-03-19 07:36:00.430 | info | (13023) [LOGIN] Reconnection in 30 seconds
bring.0 | 2021-03-19 07:36:00.429 | warn | (13023) Error: Cannot Login: Error: getaddrinfo ENOTFOUND api.getbring.com
bring.0 | 2021-03-19 07:36:00.234 | debug | (13023) [POLL] Poll all lists
bring.0 | 2021-03-19 07:35:30.233 | info | (13023) [LOGIN] Reconnection in 30 seconds
bring.0 | 2021-03-19 07:35:30.232 | warn | (13023) Error: Cannot Login: Error: getaddrinfo ENOTFOUND api.getbring.com
bring.0 | 2021-03-19 07:35:00.227 | info | (13023) [LOGIN] Reconnection in 30 seconds
bring.0 | 2021-03-19 07:35:00.226 | warn | (13023) Error: Cannot Login: Error: getaddrinfo ENOTFOUND api.getbring.com
bring.0 | 2021-03-19 07:34:45.224 | debug | (13023) system.adapter.admin.0: logging true
bring.0 | 2021-03-19 07:34:30.234 | warn | (13023) Error: Cannot get lists: Error: getaddrinfo ENOTFOUND api.getbring.com
bring.0 | 2021-03-19 07:34:30.227 | debug | (13023) [POLL] Poll all lists
bring.0 | 2021-03-19 07:34:30.225 | warn | (13023) Error: Cannot get user settings: Error: getaddrinfo ENOTFOUND api.getbring.com
bring.0 | 2021-03-19 07:34:30.216 | info | (13023) [LOGIN] Reconnection in 30 seconds
bring.0 | 2021-03-19 07:34:30.215 | warn | (13023) Error: Cannot Login: Error: getaddrinfo ENOTFOUND api.getbring.com

**Versions:**
 - Adapter version: 1.7.7
 - JS-Controller version: 3.2.16
 - Node version: 12.21.0
 - NPM Version: 7.6.3
 - Operating system: Linux

**Comment by foxriver76** [comment]
Internet Verbindung geht? Kann den Namen nicht auflösen also problem mit dem dns Server

**Comment by buehlisiobroker** [comment]
Ja,. meine Internet Verbindung funktioniert. Sonst hätte ich diesen Beitrag nicht schrieben können. Aber ist alles leider etwas seltsam, wenn ich die App im Mobiltelefon öffne, dann sind hier alle Artikel korrekt vorhanden und in der API, also über Internetseite ist alles leer. Der Login funktioniert, also gibt es scheinbar ein Problem bei der App Infrastruktur beim Anbieter. Sorry nochmals......!
