### ISSUE TITLE
Adapter bricht immer wieder

### ISSUE THREAD

**Issue by totocotonio** [foxriver76/ioBroker.bring#83]
Hallo,
ich habe immer wieder das Problem das der Adapter nicht Grün wird.
Folgender Fehler im Log.

Error: Cannot get lists: Error: connect ECONNREFUSED 127.0.0.1:443

Woran kann denn das liegen?

**Comment by totocotonio** [comment]
Hi, hat keiner eine Idee?

**Comment by foxriver76** [comment]
Not really an idea, just read that agent-base < 5 lead to such problems.
`cd /opt/iobroker/`
`npm ls agent-base`

**Comment by totocotonio** [comment]
Hi,
erst einmal Danke.
>Hier ist das >ergebnis.

`iobroker.inst@3.0.0 /opt/iobroker
├─┬ iobroker.alexa2@3.11.2
│ └─┬ @sentry/node@6.14.0
│   └─┬ https-proxy-agent@5.0.0
│     └── agent-base@6.0.2
├─┬ iobroker.iot@1.8.24
│ └─┬ jsdom@17.0.0
│   └─┬ http-proxy-agent@4.0.1
│     └── agent-base@6.0.2  deduped
├─┬ iobroker.vis-icontwo@0.84.0
│ └─┬ npm@8.3.0
│   └─┬ make-fetch-happen@9.1.0
│     ├─┬ http-proxy-agent@4.0.1
│     │ └── agent-base@6.0.2
│     ├─┬ https-proxy-agent@5.0.0
│     │ └── agent-base@6.0.2  deduped
│     └─┬ socks-proxy-agent@6.1.0
│       └── agent-base@6.0.2  deduped
├─┬ iobroker.web-speedy@0.2.0 (github:DrozmotiX/ioBroker.web-speedy#629f35c43f46                           f62ee5d9113c0df80c0f9a1c4b04)
│ └─┬ speedtest-net@1.6.2
│   ├─┬ http-proxy-agent@2.1.0
│   │ └── agent-base@4.3.0
│   └─┬ https-proxy-agent@3.0.1
│     └── agent-base@4.3.0  deduped
└─┬ iobroker.zigbee@1.6.6
  └─┬ zigbee-herdsman-converters@14.0.316
    └─┬ https-proxy-agent@5.0.0
      └── agent-base@6.0.2
`

**Comment by foxriver76** [comment]
Used in iobroker.web-speedy.

https://github.com/DrozmotiX/ioBroker.web-speedy/pull/160 Would increase it to a version > 5. 

However, you could uninstall the module if not too much is depending on it, like custom configuration of States and then see if it works. So we could at least determine if this is the real reason.

**Comment by totocotonio** [comment]
Hi,
ok aber wast webspedy mit Bring zu tun?

**Comment by foxriver76** [comment]
It seems like that it also affects requests made in other modules, according to some GH issues, thus it is the only clue I have
